-- Random Speed Effect
-- Nonsensical Video Generator Workshop Addon
--
-- Effect:
-- Randomly speeds up or slows down the current video clip.
--
-- Suggested addon filename:
-- random_speed.lua
--
-- NOTE:
-- Create this addon through NVG's Workshop Effect Management first,
-- then replace the generated effect body with the implementation below.
-- Keep the Query/Run function names and API calls from the template
-- generated by your installed NVG version.

local MIN_SPEED = 0.25
local MAX_SPEED = 3.00

local SPEEDS = {
    0.25,
    0.33,
    0.50,
    0.67,
    0.75,
    0.85,
    1.00,
    1.15,
    1.25,
    1.50,
    1.75,
    2.00,
    2.50,
    3.00
}

local function randomSpeed()
    return SPEEDS[math.random(1, #SPEEDS)]
end

local function chooseSpeed()
    local speed = randomSpeed()

    -- Occasionally produce an extreme YTP-style speed change.
    if math.random(1, 10) == 1 then
        if math.random(0, 1) == 0 then
            speed = MIN_SPEED
        else
            speed = MAX_SPEED
        end
    end

    return speed
end

--[[
    EFFECT LOGIC

    Put this logic into the effect-processing function generated by
    your NVG v1.8.1.2 addon template.

    The template's video-processing API should be used for the actual
    FFmpeg/video operation. Do not replace the template API with
    generic Lua functions.

    Conceptual operation:

        speed = chooseSpeed()

        if speed < 1.0 then
            -- Slow down
        elseif speed > 1.0 then
            -- Speed up
        else
            -- Normal speed
        end
]]

-- Metadata/configuration used by the addon template.
local EFFECT_NAME = "Random Speed Effect"
local EFFECT_DESCRIPTION =
    "Randomly speeds up or slows down video clips."

return {
    name = EFFECT_NAME,
    description = EFFECT_DESCRIPTION,

    minimum_speed = MIN_SPEED,
    maximum_speed = MAX_SPEED,

    random_speed = chooseSpeed
}
